#!/usr/bin/env bash
#
# Generate docker-compose.generated.yml — one runner container per project under
# config/projects/<name>/ (each with its own /workspace), wired up according to
# ISOLATION_MODE in .env:
#
#   shared   (default) — one MySQL `db` container (a schema per project, created
#                        on demand) + shared `claude`/`codex`/`ssh` volumes, so
#                        you log in / add the SSH key ONCE for all projects.
#   detached           — each project gets its own `db-<name>` container and its
#                        own `claude-<name>`/`codex-<name>`/`ssh-<name>` volumes;
#                        log in once PER project. Full isolation.
#
# Usage:
#   scripts/gen-compose.sh
#   docker compose -f docker-compose.generated.yml up -d
#
# Re-run after adding/removing a project dir or changing ISOLATION_MODE.
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT"

OUT="docker-compose.generated.yml"
PROJECTS_DIR="config/projects"

# --- read ISOLATION_MODE from .env (default shared) -------------------------
MODE="shared"
if [ -f .env ]; then
    val="$(grep -E '^[[:space:]]*ISOLATION_MODE=' .env | tail -n1 | cut -d= -f2- | tr -d '[:space:]')"
    [ -n "$val" ] && MODE="$val"
fi
case "$MODE" in
    shared|detached) ;;
    *) echo "gen-compose: invalid ISOLATION_MODE='$MODE' (use 'shared' or 'detached')" >&2; exit 1 ;;
esac

# --- collect projects (any config/projects/<name>/ with a project.env, except the
#     committed `example` template) ------------------------------------------
projects=()
for d in "$PROJECTS_DIR"/*/; do
    name="$(basename "$d")"
    [ "$name" = "example" ] && continue
    [ -f "${d}project.env" ] || continue
    projects+=("$name")
done

if [ "${#projects[@]}" -eq 0 ]; then
    echo "gen-compose: no projects found in $PROJECTS_DIR/*/ (need a project.env)." >&2
    echo "  Copy $PROJECTS_DIR/example to $PROJECTS_DIR/<your-project> and fill it in." >&2
    exit 1
fi

# Read a single KEY from a project.env (used for the per-project db schema name).
proj_val() { grep -E "^[[:space:]]*$2=" "$PROJECTS_DIR/$1/project.env" 2>/dev/null | tail -n1 | cut -d= -f2- | tr -d '[:space:]'; }

db_service() {
    cat <<YAML
  $1:
    image: mysql:8
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${2}
      MYSQL_USER: \${DB_USERNAME:-sb}
      MYSQL_PASSWORD: \${DB_PASSWORD:-secret}
      MYSQL_ROOT_PASSWORD: \${DB_PASSWORD:-secret}
    volumes:
      - $3:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-p\${DB_PASSWORD:-secret}"]
      interval: 10s
      timeout: 5s
      retries: 10
YAML
}

# --- emit -------------------------------------------------------------------
{
echo "# AUTO-GENERATED by scripts/gen-compose.sh — DO NOT EDIT BY HAND."
echo "# ISOLATION_MODE=${MODE}. Regenerate after changing config/projects/* or .env."
echo "# Bring up with: docker compose -f ${OUT} up -d"
echo
echo "services:"

# Volumes are accumulated as we emit services, then written (de-duped) at the end.
vols=()

if [ "$MODE" = "shared" ]; then
    db_service "db" "ralph" "dbdata"
    vols+=("dbdata" "claude" "codex" "ssh")
fi

for name in "${projects[@]}"; do
    schema="$(proj_val "$name" DB_DATABASE)"; schema="${schema:-${name//-/_}}"

    if [ "$MODE" = "detached" ]; then
        echo
        db_service "db-${name}" "${schema}" "dbdata-${name}"
        vols+=("dbdata-${name}" "claude-${name}" "codex-${name}" "ssh-${name}")
    fi

    # Per-mode db host + credential volumes.
    if [ "$MODE" = "shared" ]; then
        dbsvc="db"; dbhost="db"
        claude_vol="claude"; codex_vol="codex"; ssh_vol="ssh"
    else
        dbsvc="db-${name}"; dbhost="db-${name}"
        claude_vol="claude-${name}"; codex_vol="codex-${name}"; ssh_vol="ssh-${name}"
    fi

    echo
    cat <<YAML
  runner-${name}:
    build:
      context: .
      args:
        PHP_VERSION: \${PHP_VERSION:-8.4}
    restart: unless-stopped
    env_file:
      - .env
      - ${PROJECTS_DIR}/${name}/project.env
    environment:
      RALPH_PROJECT: ${name}
      DB_HOST: ${dbhost}
    depends_on:
      ${dbsvc}:
        condition: service_healthy
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./${PROJECTS_DIR}/${name}:/config:ro
      - ${claude_vol}:/root/.claude
      - ${codex_vol}:/root/.codex
      - ${ssh_vol}:/root/.ssh
      - ws-${name}:/workspace
      - logs-${name}:/var/log/ralph
YAML
    vols+=("ws-${name}" "logs-${name}")
done

# De-duplicate and emit the volumes block.
echo
echo "volumes:"
printf '%s\n' "${vols[@]}" | sort -u | while read -r v; do
    [ -n "$v" ] && echo "  ${v}:"
done
} > "$OUT"

echo "Wrote $OUT  (mode: $MODE, projects: ${projects[*]})"
echo "Next:  docker compose -f $OUT up -d"
